Update package-scripts-powershell-folder.yml
Signed-off-by: LUIZ HAMILTON ROBERTO DA SILVA <luizhamilton.lhr@gmail.com>

diff --git a/.github/workflows/package-scripts-powershell-folder.yml b/.github/workflows/package-scripts-powershell-folder.yml
--- a/.github/workflows/package-scripts-powershell-folder.yml
+++ b/.github/workflows/package-scripts-powershell-folder.yml
@@ -45,9 +45,9 @@ jobs:
         run: |
           echo "Preparing the Scripts-PowerShell folder..."
           mkdir -p Scripts-PowerShell
-          cp -r Core-ScriptLibrary/* Scripts-PowerShell/ || echo "Core-ScriptLibrary not found, skipping."
-          cp LICENSE Scripts-PowerShell/ || echo "LICENSE not found, skipping."
-          cp README.md Scripts-PowerShell/ || echo "README.md not found, skipping."
+          cp -r Core-ScriptLibrary/* Windows-SysAdmin-ProSuite/ || echo "Core-ScriptLibrary not found, skipping."
+          cp LICENSE Windows-SysAdmin-ProSuite/ || echo "LICENSE not found, skipping."
+          cp README.md Windows-SysAdmin-ProSuite/ || echo "README.md not found, skipping."
 
       # Step 5: Update Project File
       - name: Update Project File
@@ -71,8 +71,8 @@ jobs:
               <NoWarn>NU5110;NU5111;NU5123</NoWarn>
             </PropertyGroup>
             <ItemGroup>
-              <None Include="Scripts-PowerShell/**/*.*" Pack="true" PackagePath="content/" />
-              <None Remove="Scripts-PowerShell/SysAdmin-Tools/GroupPolicyObjects-Templates/**" />
+              <None Include="Windows-SysAdmin-ProSuite/**/*.*" Pack="true" PackagePath="content/" />
+              <None Remove="Windows-SysAdmin-ProSuite/SysAdmin-Tools/GroupPolicyObjects-Templates/**" />
             </ItemGroup>
           </Project>
           EOF
